# Container only for development and testing! purpose
version: "3.9"
services:
  postgresql:
    build:
      context: ../../docker/postgresql
      dockerfile: Dockerfile
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
      - POSTGRES_DATABASES=${POSTGRES_DATABASES}
    ports:
      - ${POSTGRES_PORT}
    networks:
      - internal-net
volumes:
  postgresql-data:
    name: "postgresql-data"
networks:
  internal-net:
    name: internal-net
    driver: bridge