# Container only for development and testing! purpose
version: "3.8"
services:
  postgresql:
    container_name: postgresql
    build:
      context: ../../docker/postgresql
      dockerfile: Dockerfile
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
      - POSTGRES_DATABASES=${POSTGRES_DATABASES}
    ports:
      - ${POSTGRES_PORT}
    networks:
      - postgresql_backend_net
  keycloak:
    container_name: keycloak
    build:
      context: ../../docker/keycloak
      dockerfile: Dockerfile
    ports:
      - "${KEYCLOAK_PORT}"
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgresql
      - DB_SCHEMA=${KEYCLOAK_DB_SCHEMA}
      - DB_DATABASE=${KEYCLOAK_DB_NAME}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_LOGLEVEL=${KEYCLOAK_LOGLEVEL}
      # Keycloak has the option run behind a reverse proxy
      - PROXY_ADDRESS_FORWARDING=${PROXY_ADDRESS_FORWARDING}
      - KC_PROXY=${KC_PROXY}
    networks:
      - postgresql_backend_net
networks:
  postgresql_backend_net:
    driver: bridge
