# Container only for development and testing! purpose
version: "3.8"
services:
  postgresql:
    container_name: postgresql
    build:
      context: ../../docker/postgresql
      dockerfile: Dockerfile
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
      - POSTGRES_DATABASES=${POSTGRES_DATABASES}
    ports:
      - ${POSTGRES_PORT}
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
networks:
  backend_net:
    driver: bridge
